### ISSUE TITLE
切换省市区时报错,样式显示混乱

### ISSUE THREAD

**Issue by liLongCoding** [zwlccc/ionic4-city-picker#1]
![image](https://user-images.githubusercontent.com/28978830/57434474-a95da880-726d-11e9-897c-4b5e32add775.png)

**Comment by zwlccc** [comment]
1.download ionic core([ionic](https://github.com/ionic-team/ionic));

2.modify picker-column.tsx file([just here](https://github.com/zwlccc/ionic4-city-picker/blob/master/picker-column/picker-column.tsx));

3.npm run build ionic/core;

4.copy dist folder file to node_modules\@ionic\core,overlay folder.
