### ISSUE TITLE
@ionic/core 4.11.5 选项重叠

### ISSUE THREAD

**Issue by rimuweinuan** [zwlccc/ionic4-city-picker#10]
在@ionic/core 4.11.5 出现选项重叠的情况时，修改内容如“b)4.4.2 < ionic version <= 4.11.5”，路径不对。应该是在“/node_modules/@ionic/angular/node_modules/@ionic/core/dist/esm”，这样浏览器才能奏效。

**Comment by zwlccc** [comment]
路径没错，是“node_modules\@ionic\core\dist\esm”

**Comment by rimuweinuan** [comment]
> 路径没错，是“node_modules@ionic\core\dist\esm”

1.“/node_modules/@ionic/angular/node_modules/@ionic/core/dist/esm”这样浏览器才能奏效。
2.疑问：除了改这个还有什么要改的吗？在真机没凑效。

**Comment by rimuweinuan** [comment]
改的方法没错。对我来说，路径可能有点差别。
1.谷歌浏览器调试奏效路径：/node_modules/@ionic/angular/node_modules/@ionic/core/dist/esm
2.安卓真机奏效路径：/node_modules/@ionic/angular/node_modules/@ionic/core/dist/esm-es5

**Comment by rimuweinuan** [comment]
改的方法没错。对我来说，路径可能有点差别。
1.谷歌浏览器调试奏效路径：/node_modules/@ionic/angular/node_modules/@ionic/core/dist/esm
2.安卓真机奏效路径：/node_modules/@ionic/angular/node_modules/@ionic/core/dist/esm-es5
