### ISSUE TITLE
用ionic4/angular,使用picker出了点问题

### ISSUE THREAD

**Issue by pppp0836** [zwlccc/ionic4-city-picker#3]
你好，我请教你一下，我这项目picker有三列，每列选择了后另两列都会联动，现在联动的时候，选项都会重叠，请问有解决方法吗

**Comment by pppp0836** [comment]
@zwlccc  能加下扣扣沟通一下吗

**Comment by zwlccc** [comment]
你好，最近在忙公司项目的事，请问你是遇到什么问题了吗？

发送自 Windows 10 版邮件<https://go.microsoft.com/fwlink/?LinkId=550986>应用

________________________________
发件人: pppp0836 <notifications@github.com>
发送时间: Thursday, June 20, 2019 8:09:49 PM
收件人: zwlccc/ionic4-city-picker
抄送: zwluo; Mention
主题: Re: [zwlccc/ionic4-city-picker] 用ionic4/angular,使用picker出了点问题 (#3)


@zwlccc<https://github.com/zwlccc> 能加下扣扣沟通一下吗

―

**Comment by zwlccc** [comment]
联动的话，现在ionic4官方的版本就存在这个问题，需要去下载一下源码，改一个文件，编译一下，再仍回node_modules\@ionic\core，就好了。README都有说过的。

**Comment by pppp0836** [comment]
@zwlccc  你意思是下载官方那个tsx吗，然后编译成picker-column.js,对吧，我看过你之前在官方post的那个issue,我没下载源码编译，我直接修改项目目录中 按你那个说明，修改node_modules@ionic\core\dist\collection\components\picker-column.js 这个文件，但是没有效果，不知道是哪里没弄对

**Comment by pppp0836** [comment]
@zwlccc 我照readme试试，谢谢

**Comment by zwlccc** [comment]
@pppp0836 你下载源码后，进入code文件夹，去修改picker-column.tsx文件，修改完后，在code文件夹下编译，再编译后的dist下的全部文件覆盖node_modules@ionic\core\dist

**Comment by rimuweinuan** [comment]
> @zwlccc 你意思是下载官方那个tsx吗，然后编译成picker-column.js,对吧，我看过你之前在官方post的那个issue,我没下载源码编译，我直接修改项目目录中 按你那个说明，修改node_modules@ionic\core\dist\collection\components\picker-column.js 这个文件，但是没有效果，不知道是哪里没弄对

请问这个tsx怎么编译成js？
