### ISSUE TITLE
UnhandledPromiseRejectionWarning: Error: Command failed: npm run build

### ISSUE THREAD

**Issue by 2yue** [zwlccc/ionic4-city-picker#5]
执行 npm run build ionic/core 提示 ，麻烦帮忙看看 谢谢

13 verbose stack Error: @ionic/core@4.6.0 css.sass: `sass src/css:./css`
13 verbose stack Exit status 1
13 verbose stack     at EventEmitter.<anonymous> (F:\Program Files\nodejs\node_modules\npm\node_modules\npm-lifecycle\index.js:301:16)
13 verbose stack     at EventEmitter.emit (events.js:189:13)
13 verbose stack     at ChildProcess.<anonymous> (F:\Program Files\nodejs\node_modules\npm\node_modules\npm-lifecycle\lib\spawn.js:55:14)
13 verbose stack     at ChildProcess.emit (events.js:189:13)
13 verbose stack     at maybeClose (internal/child_process.js:970:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:259:5)
14 verbose pkgid @ionic/core@4.6.0

**Comment by zwlccc** [comment]
应该是Node版本的问题，我得是Node-10.15

**Comment by 2yue** [comment]
好的 谢谢  我试试 - -
