### ISSUE TITLE
切换城市或区的时候样式混乱

### ISSUE THREAD

**Issue by iwantacook** [zwlccc/ionic4-city-picker#7]
![image](https://user-images.githubusercontent.com/25666051/62860347-8510dc80-bd32-11e9-94a4-a0f19a436156.png)

**Comment by huang1999** [comment]
我参考这篇文章里看zwlccc的方法就可以了 https://github.com/ionic-team/ionic/issues/17664

**Comment by zwlccc** [comment]
@iwantacook 具体文件在[这里](https://github.com/zwlccc/ionic4-city-picker/blob/master/picker-column/picker-column.tsx)，修改，编译即可解决。README.md有介绍解决方案。

**Comment by iwantacook** [comment]
@huang1999 @zwlccc 谢谢，空的时候，我们再尝试弄一下，非常感谢！
